### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by speermahi** [snapshotpl/ZfSnapPhpError#1]
On -> composer install  "getting message"

```
 - snapshotpl/zf-snap-php-error dev-master requires joseph-lenton/php-error dev-fixes as dev-master -> no matching package found.
```

**Comment by snapshotpl** [comment]
How looks like your composer.json?

**Comment by speermahi** [comment]
{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for ZF2",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://framework.zend.com/",
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.3._",
        "zendframework/zend-developer-tools":"dev-master",
        "zendframework/zftool": "dev-master",
        "zendframework/zenddiagnostics": "1.0._@dev",
        "doctrine/doctrine-module": "dev-master",
        "zf-commons/zfc-twig": "dev-master",
        "doctrine/doctrine-orm-module" : "dev-master",
        "snapshotpl/zf-snap-php-error" : "dev-master"
    }
}

**Comment by snapshotpl** [comment]
Ok, so now look at installation guide :) https://github.com/snapshotpl/ZfSnapPhpError#how-to-install

**Comment by speermahi** [comment]
still the same result - after calling ("snapshotpl/zf-snap-php-error" : "1.*")

```
Problem 1
    - Installation request for snapshotpl/zf-snap-php-error 1.* -> satisfiable by snapshotpl/zf-snap-php-error[1.0.0].
    - snapshotpl/zf-snap-php-error 1.0.0 requires joseph-lenton/php-error dev-fixes as dev-master -> no matching package found.
```

**Comment by snapshotpl** [comment]
Ok, I will check this. Maybe composer change something. Are you use current version of composer?

**Comment by speermahi** [comment]
Composer version "e23665be591c6c5657b791a372c45136b2de3a7a"

**Comment by snapshotpl** [comment]
Try this. Change is in minimum-stability

``` json
{
    "minimum-stability": "dev",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/snapshotpl/PHP-Error"
        }
    ],
    "require": {
        "snapshotpl/zf-snap-php-error": "1.*"
    }
}
```

**Comment by speermahi** [comment]
thanks i will give a try

**Comment by snapshotpl** [comment]
@polargold and?

**Comment by sirthxalot** [comment]
Hi are you still supporting this module?

Because I do have the same issue:

>   Problem 1
>     - Installation request for snapshotpl/zf-snap-php-error 1.\* -> satisfiable by snapshotpl/zf-snap-php-error[1.0.0].
>     - snapshotpl/zf-snap-php-error 1.0.0 requires joseph-lenton/php-error dev-fixes as dev-master -> no matching package found.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
> 
> Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
> 
> ...sta.zf2.app>php composer.phar self-update
> You are already using composer version 24168d9d5c0ab0103cd6d17a86dea99c11196cd3. 

My composer.json looks like this:

```
{
    "name":         "STA-ZF2 Skeleton-Application",
    "description":  "Skeleton-Application, based on the Zend Framework 2.",
    "version":      "0.0.4",
    "keywords":     ["sta", "zf2", "skeleton", "application"],
    "homepage":     "...",
    "type":         "project",
    "license":      "MIT-License",
    "support": {
        "issues":   "...",
        "wiki":     "...",
        "source":   "..."
    },
    "minimum-stability": "dev",
    "require": {
        "php":                                  ">=5.5.0",
        "zendframework/zendframework":          "2.5.*",
        "joseph-lenton/php-error":              "dev-master",
        "snapshotpl/zf-snap-php-error":         "1.*"
    },
    "require-dev": {
        "zendframework/zend-developer-tools":   "dev-master",
        "bjyoungblood/bjy-profiler":            "dev-master",
        "snapshotpl/zf-snap-event-debugger":    "dev-master",
        "jhuet/zdt-logger-module":              "dev-master"
    },
    "config": {
        "process-timeout": 1800
    }
}

```

**Comment by snapshotpl** [comment]
@sirthxalot Yes :) I see that your composer missing repository (more https://github.com/snapshotpl/ZfSnapPhpError#how-to-install)

**Comment by sirthxalot** [comment]
**Yes Sir!**
Everything worked for me since I add the repository :sleepy: 
Thank you for solving my issue and the provided packages from you (my favourites).

Cheerio
_SirThxAlot_

**Comment by snapshotpl** [comment]
@sirthxalot glad to hear that!
